-- 회사 내부 마케팅 퍼널 대시보드
update public.roles set name = '회사 내부' where id = 'employee';
update public.roles set name = '강의 수강생' where id = 'trainee';

create table if not exists public.marketing_products (
    id uuid primary key default gen_random_uuid(),
    brand text not null,
    name text not null,
    slug text not null unique,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.daily_marketing_metrics (
    id bigint generated by default as identity primary key,
    product_id uuid not null references public.marketing_products(id) on delete cascade,
    metric_date date not null,
    content_views integer not null default 0 check (content_views >= 0),
    content_posts_count integer not null default 0 check (content_posts_count >= 0),
    keyword_search_volume integer not null default 0 check (keyword_search_volume >= 0),
    site_visits integer not null default 0 check (site_visits >= 0),
    cafe24_orders integer not null default 0 check (cafe24_orders >= 0),
    cafe24_revenue bigint not null default 0 check (cafe24_revenue >= 0),
    coupang_orders integer not null default 0 check (coupang_orders >= 0),
    coupang_revenue bigint not null default 0 check (coupang_revenue >= 0),
    smartstore_orders integer not null default 0 check (smartstore_orders >= 0),
    smartstore_revenue bigint not null default 0 check (smartstore_revenue >= 0),
    ad_spend bigint not null default 0 check (ad_spend >= 0),
    source text not null default 'manual' check (source in ('manual', 'api', 'import')),
    source_details jsonb not null default '{}'::jsonb,
    created_by uuid references public.profiles(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (product_id, metric_date)
);

create table if not exists public.marketing_contents (
    id uuid primary key default gen_random_uuid(),
    product_id uuid not null references public.marketing_products(id) on delete cascade,
    channel text not null check (channel in ('naver_blog', 'naver_cafe', 'other')),
    title text not null,
    url text not null unique,
    published_at timestamptz,
    is_active boolean not null default true,
    created_by uuid references public.profiles(id) on delete set null,
    created_at timestamptz not null default now()
);

create table if not exists public.daily_content_metrics (
    id bigint generated by default as identity primary key,
    content_id uuid not null references public.marketing_contents(id) on delete cascade,
    metric_date date not null,
    views integer not null default 0 check (views >= 0),
    source text not null default 'manual' check (source in ('manual', 'api', 'import')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (content_id, metric_date)
);

create index if not exists daily_marketing_metrics_date_idx
    on public.daily_marketing_metrics (metric_date desc, product_id);
create index if not exists daily_content_metrics_date_idx
    on public.daily_content_metrics (metric_date desc, content_id);

insert into public.marketing_products (brand, name, slug, sort_order)
values
    ('이너리움', '갈라431', 'innerium-gala431', 1),
    ('이너리움', '민티431', 'innerium-minti431', 2),
    ('유랄', '통감크림', 'yural-tonggam-cream', 3),
    ('유랄', '명가본환', 'yural-myeongga-bonhwan', 4)
on conflict (slug) do update
set brand = excluded.brand,
    name = excluded.name,
    sort_order = excluded.sort_order,
    is_active = true,
    updated_at = now();

create or replace function public.is_internal_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select coalesce(auth.jwt() ->> 'role', '') = 'service_role'
        or exists (
            select 1
            from public.profiles
            where id = auth.uid()
              and role_id in ('admin', 'employee')
              and approval_status = 'approved'
        );
$$;

alter table public.marketing_products enable row level security;
alter table public.daily_marketing_metrics enable row level security;
alter table public.marketing_contents enable row level security;
alter table public.daily_content_metrics enable row level security;

drop policy if exists internal_read_products on public.marketing_products;
create policy internal_read_products on public.marketing_products
for select to authenticated using (public.is_internal_user());

drop policy if exists admin_manage_products on public.marketing_products;
create policy admin_manage_products on public.marketing_products
for all to authenticated
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

drop policy if exists internal_read_daily_metrics on public.daily_marketing_metrics;
create policy internal_read_daily_metrics on public.daily_marketing_metrics
for select to authenticated using (public.is_internal_user());

drop policy if exists internal_write_daily_metrics on public.daily_marketing_metrics;
create policy internal_write_daily_metrics on public.daily_marketing_metrics
for insert to authenticated with check (public.is_internal_user());

drop policy if exists internal_update_daily_metrics on public.daily_marketing_metrics;
create policy internal_update_daily_metrics on public.daily_marketing_metrics
for update to authenticated
using (public.is_internal_user())
with check (public.is_internal_user());

drop policy if exists admin_delete_daily_metrics on public.daily_marketing_metrics;
create policy admin_delete_daily_metrics on public.daily_marketing_metrics
for delete to authenticated using (public.is_current_user_admin());

drop policy if exists internal_read_contents on public.marketing_contents;
create policy internal_read_contents on public.marketing_contents
for select to authenticated using (public.is_internal_user());

drop policy if exists internal_write_contents on public.marketing_contents;
create policy internal_write_contents on public.marketing_contents
for insert to authenticated with check (public.is_internal_user());

drop policy if exists internal_update_contents on public.marketing_contents;
create policy internal_update_contents on public.marketing_contents
for update to authenticated
using (public.is_internal_user())
with check (public.is_internal_user());

drop policy if exists admin_delete_contents on public.marketing_contents;
create policy admin_delete_contents on public.marketing_contents
for delete to authenticated using (public.is_current_user_admin());

drop policy if exists internal_read_content_metrics on public.daily_content_metrics;
create policy internal_read_content_metrics on public.daily_content_metrics
for select to authenticated using (public.is_internal_user());

drop policy if exists internal_write_content_metrics on public.daily_content_metrics;
create policy internal_write_content_metrics on public.daily_content_metrics
for insert to authenticated with check (public.is_internal_user());

drop policy if exists internal_update_content_metrics on public.daily_content_metrics;
create policy internal_update_content_metrics on public.daily_content_metrics
for update to authenticated
using (public.is_internal_user())
with check (public.is_internal_user());

drop policy if exists admin_delete_content_metrics on public.daily_content_metrics;
create policy admin_delete_content_metrics on public.daily_content_metrics
for delete to authenticated using (public.is_current_user_admin());
