-- 네이버 카페 본문을 열지 않고 목록 조회수 스냅샷과 일 증가분을 저장한다.

alter table public.daily_content_metrics
    add column if not exists cumulative_views bigint
        check (cumulative_views is null or cumulative_views >= 0),
    add column if not exists collection_status text not null default 'complete'
        check (collection_status in ('complete', 'baseline', 'gap', 'decrease', 'missing', 'error')),
    add column if not exists source_details jsonb not null default '{}'::jsonb;

comment on column public.daily_content_metrics.views is
    '블로그는 날짜별 방문자 수, 카페는 직전 정상 스냅샷 대비 조회 증가분';
comment on column public.daily_content_metrics.cumulative_views is
    '네이버 카페 목록에 표시된 수집 시점 누적 조회수';

create table if not exists public.marketing_cafe_article_state (
    id uuid primary key default gen_random_uuid(),
    content_id uuid not null unique
        references public.marketing_contents(id) on delete cascade,
    product_id uuid not null
        references public.marketing_products(id) on delete cascade,
    cafe_id bigint not null check (cafe_id > 0),
    article_id bigint not null check (article_id > 0),
    cafe_alias text not null check (cafe_alias ~ '^[A-Za-z0-9][A-Za-z0-9_-]{1,49}$'),
    menu_id integer check (menu_id is null or menu_id > 0),
    source_url text not null,
    published_date date not null,
    source_details jsonb not null default '{}'::jsonb,
    last_cumulative_views bigint
        check (last_cumulative_views is null or last_cumulative_views >= 0),
    last_observed_at timestamptz,
    last_metric_date date,
    last_seen_run_id uuid
        references public.marketing_ingestion_runs(id) on delete set null,
    is_active boolean not null default true,
    consecutive_errors integer not null default 0 check (consecutive_errors >= 0),
    last_error text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (product_id, cafe_id, article_id)
);

create table if not exists public.marketing_cafe_observations (
    id bigint generated by default as identity primary key,
    run_id uuid not null
        references public.marketing_ingestion_runs(id) on delete cascade,
    product_id uuid not null
        references public.marketing_products(id) on delete cascade,
    cafe_id bigint not null check (cafe_id > 0),
    article_id bigint not null check (article_id > 0),
    menu_id integer check (menu_id is null or menu_id > 0),
    cumulative_views bigint
        check (cumulative_views is null or cumulative_views >= 0),
    observed_at timestamptz not null,
    error_code text,
    error_message text,
    source_details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique (run_id, product_id, cafe_id, article_id),
    check (
        (cumulative_views is not null and error_code is null)
        or (cumulative_views is null and error_code is not null)
    )
);

create index if not exists marketing_cafe_state_product_active_idx
    on public.marketing_cafe_article_state (product_id, is_active, published_date desc);
create index if not exists marketing_cafe_state_run_idx
    on public.marketing_cafe_article_state (last_seen_run_id, product_id);
create index if not exists marketing_cafe_observations_run_idx
    on public.marketing_cafe_observations (run_id, product_id);

alter table public.marketing_cafe_article_state enable row level security;
alter table public.marketing_cafe_observations enable row level security;

drop policy if exists internal_read_marketing_cafe_state
    on public.marketing_cafe_article_state;
create policy internal_read_marketing_cafe_state
on public.marketing_cafe_article_state
for select to authenticated
using (public.is_internal_user());

drop policy if exists internal_read_marketing_cafe_observations
    on public.marketing_cafe_observations;
create policy internal_read_marketing_cafe_observations
on public.marketing_cafe_observations
for select to authenticated
using (public.is_internal_user());

create or replace function public.finalize_naver_cafe_collection(p_run_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    run_record public.marketing_ingestion_runs;
    expected_entry record;
    target_product public.marketing_products;
    expected_count integer;
    source_count integer;
    observed_count integer;
    baseline_count integer;
    invalid_count integer;
    missing_count integer;
    product_delta bigint;
    product_complete boolean;
    all_complete boolean := true;
    total_succeeded integer := 0;
    total_failed integer := 0;
    product_results jsonb := '[]'::jsonb;
    finalize_result jsonb;
begin
    if coalesce(auth.jwt() ->> 'role', '') <> 'service_role' then
        raise exception 'service role required';
    end if;

    select *
    into run_record
    from public.marketing_ingestion_runs
    where id = p_run_id
      and provider = 'naver_cafe'
    for update;

    if run_record.id is null then
        raise exception 'naver cafe collection run not found';
    end if;
    if run_record.status <> 'running' then
        return coalesce(run_record.details -> 'finalize_result', run_record.details);
    end if;
    if jsonb_typeof(run_record.details -> 'expected_by_product') <> 'object' then
        raise exception 'expected product counts are missing';
    end if;

    for expected_entry in
        select key, value
        from jsonb_each_text(run_record.details -> 'expected_by_product')
    loop
        expected_count := expected_entry.value::integer;
        select *
        into target_product
        from public.marketing_products
        where slug = expected_entry.key
          and is_active;
        if target_product.id is null then
            raise exception 'unknown marketing product: %', expected_entry.key;
        end if;

        select count(*)::integer
        into source_count
        from public.marketing_cafe_article_state
        where product_id = target_product.id
          and last_seen_run_id = p_run_id;

        select count(*) filter (
                   where observations.cumulative_views is not null
                     and observations.error_code is null
               )::integer
        into observed_count
        from public.marketing_cafe_observations observations
        where observations.run_id = p_run_id
          and observations.product_id = target_product.id;

        insert into public.daily_content_metrics (
            content_id,
            metric_date,
            views,
            cumulative_views,
            source,
            collection_status,
            source_details,
            updated_at
        )
        select
            state.content_id,
            run_record.metric_date,
            case
                when state.last_metric_date = run_record.metric_date
                     and existing.id is not null
                    then existing.views
                when state.last_cumulative_views is null then 0
                when state.last_observed_at is null
                     or observations.observed_at - state.last_observed_at > interval '30 hours'
                    then 0
                when observations.cumulative_views < state.last_cumulative_views then 0
                else (observations.cumulative_views - state.last_cumulative_views)::integer
            end,
            observations.cumulative_views,
            'api',
            case
                when state.last_metric_date = run_record.metric_date
                     and existing.id is not null
                    then existing.collection_status
                when state.last_cumulative_views is null then 'baseline'
                when state.last_observed_at is null
                     or observations.observed_at - state.last_observed_at > interval '30 hours'
                    then 'gap'
                when observations.cumulative_views < state.last_cumulative_views then 'decrease'
                else 'complete'
            end,
            jsonb_build_object(
                'provider', 'naver_cafe',
                'run_id', p_run_id,
                'cafe_id', state.cafe_id,
                'article_id', state.article_id,
                'menu_id', coalesce(observations.menu_id, state.menu_id),
                'observed_at', observations.observed_at
            ),
            now()
        from public.marketing_cafe_article_state state
        join public.marketing_cafe_observations observations
          on observations.run_id = p_run_id
         and observations.product_id = state.product_id
         and observations.cafe_id = state.cafe_id
         and observations.article_id = state.article_id
         and observations.cumulative_views is not null
         and observations.error_code is null
        left join public.daily_content_metrics existing
          on existing.content_id = state.content_id
         and existing.metric_date = run_record.metric_date
        where state.product_id = target_product.id
          and state.last_seen_run_id = p_run_id
        on conflict (content_id, metric_date) do update
        set
            views = excluded.views,
            cumulative_views = excluded.cumulative_views,
            source = 'api',
            collection_status = excluded.collection_status,
            source_details = coalesce(public.daily_content_metrics.source_details, '{}'::jsonb)
                || excluded.source_details,
            updated_at = now();

        select
            count(*) filter (where metrics.collection_status = 'baseline')::integer,
            count(*) filter (where metrics.collection_status in ('gap', 'decrease', 'error', 'missing'))::integer,
            coalesce(sum(metrics.views) filter (
                where metrics.collection_status in ('complete', 'baseline')
            ), 0)::bigint
        into baseline_count, invalid_count, product_delta
        from public.marketing_cafe_article_state state
        left join public.daily_content_metrics metrics
          on metrics.content_id = state.content_id
         and metrics.metric_date = run_record.metric_date
        where state.product_id = target_product.id
          and state.last_seen_run_id = p_run_id;

        missing_count := greatest(expected_count - observed_count, 0);
        product_complete :=
            source_count = expected_count
            and observed_count = expected_count
            and invalid_count = 0;

        update public.marketing_cafe_article_state state
        set
            menu_id = coalesce(observations.menu_id, state.menu_id),
            last_cumulative_views = observations.cumulative_views,
            last_observed_at = observations.observed_at,
            last_metric_date = run_record.metric_date,
            consecutive_errors = 0,
            last_error = null,
            is_active = true,
            updated_at = now()
        from public.marketing_cafe_observations observations
        where observations.run_id = p_run_id
          and observations.product_id = target_product.id
          and observations.cumulative_views is not null
          and observations.error_code is null
          and state.product_id = observations.product_id
          and state.cafe_id = observations.cafe_id
          and state.article_id = observations.article_id;

        update public.marketing_cafe_article_state state
        set
            consecutive_errors = state.consecutive_errors + 1,
            last_error = observations.error_message,
            updated_at = now()
        from public.marketing_cafe_observations observations
        where observations.run_id = p_run_id
          and observations.product_id = target_product.id
          and observations.error_code is not null
          and state.product_id = observations.product_id
          and state.cafe_id = observations.cafe_id
          and state.article_id = observations.article_id;

        if source_count = expected_count then
            update public.marketing_cafe_article_state
            set is_active = (last_seen_run_id = p_run_id),
                updated_at = now()
            where product_id = target_product.id
              and is_active <> (last_seen_run_id = p_run_id);

            update public.marketing_contents contents
            set is_active = state.is_active
            from public.marketing_cafe_article_state state
            where state.product_id = target_product.id
              and contents.id = state.content_id
              and contents.is_active <> state.is_active;
        end if;

        if product_complete then
            perform public.merge_daily_marketing_metric(
                target_product.id,
                run_record.metric_date,
                jsonb_build_object(
                    'cafe_views', product_delta,
                    'data_completeness', jsonb_build_object('cafe_views', true)
                ),
                'api',
                jsonb_build_object(
                    'provider', 'naver_cafe',
                    'run_id', p_run_id,
                    'expected_count', expected_count,
                    'observed_count', observed_count,
                    'baseline_count', baseline_count
                ),
                'partial'
            );
        else
            all_complete := false;
        end if;

        total_succeeded := total_succeeded + observed_count - invalid_count;
        total_failed := total_failed + missing_count + invalid_count;
        product_results := product_results || jsonb_build_array(jsonb_build_object(
            'product_slug', target_product.slug,
            'expected_count', expected_count,
            'source_count', source_count,
            'observed_count', observed_count,
            'baseline_count', baseline_count,
            'invalid_count', invalid_count,
            'missing_count', missing_count,
            'cafe_views', case when product_complete then product_delta else null end,
            'complete', product_complete
        ));
    end loop;

    finalize_result := jsonb_build_object(
        'run_id', p_run_id,
        'metric_date', run_record.metric_date,
        'status', case when all_complete then 'success' else 'partial' end,
        'products', product_results,
        'records_succeeded', total_succeeded,
        'records_failed', total_failed
    );

    update public.marketing_ingestion_runs
    set
        status = case when all_complete then 'success' else 'partial' end,
        finished_at = now(),
        records_succeeded = greatest(total_succeeded, 0),
        records_failed = greatest(total_failed, 0),
        details = details || jsonb_build_object('finalize_result', finalize_result),
        error_message = case
            when all_complete then null
            else '일부 카페 글의 스냅샷 또는 정상 차분이 누락되었습니다.'
        end
    where id = p_run_id;

    if run_record.batch_id is not null then
        update public.marketing_ingestion_batches
        set
            status = case when all_complete then 'success' else 'partial' end,
            finished_at = now(),
            details = details || jsonb_build_object('naver_cafe', finalize_result)
        where id = run_record.batch_id;
    end if;

    return finalize_result;
end;
$$;

revoke all on function public.finalize_naver_cafe_collection(uuid) from public;
grant execute on function public.finalize_naver_cafe_collection(uuid) to service_role;

create or replace function public.prune_naver_cafe_collection_details()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    delete from public.marketing_cafe_observations
    where created_at < now() - interval '7 days';

    delete from public.daily_content_metrics metrics
    using public.marketing_contents contents
    where metrics.content_id = contents.id
      and contents.channel = 'naver_cafe'
      and metrics.metric_date < current_date - 120;
end;
$$;

revoke all on function public.prune_naver_cafe_collection_details() from public;
grant execute on function public.prune_naver_cafe_collection_details() to service_role;

do $$
declare
    existing_job bigint;
begin
    select jobid into existing_job
    from cron.job
    where jobname = 'naver-cafe-detail-retention';
    if existing_job is not null then
        perform cron.unschedule(existing_job);
    end if;
    perform cron.schedule(
        'naver-cafe-detail-retention',
        '30 18 * * *',
        'select public.prune_naver_cafe_collection_details();'
    );
end;
$$;
