-- 네이버 검색광고 계정은 제품이 아니라 브랜드 단위이므로 광고비를 별도 저장한다.

create table if not exists public.daily_brand_marketing_metrics (
    id bigint generated by default as identity primary key,
    brand text not null check (length(trim(brand)) > 0),
    metric_date date not null,
    naver_ad_spend bigint not null default 0 check (naver_ad_spend >= 0),
    source text not null default 'api' check (source in ('manual', 'api', 'import')),
    source_details jsonb not null default '{}'::jsonb,
    collected_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (brand, metric_date)
);

create index if not exists daily_brand_marketing_metrics_date_idx
    on public.daily_brand_marketing_metrics (metric_date desc, brand);

alter table public.daily_brand_marketing_metrics enable row level security;

drop policy if exists internal_read_daily_brand_marketing_metrics
    on public.daily_brand_marketing_metrics;
create policy internal_read_daily_brand_marketing_metrics
on public.daily_brand_marketing_metrics
for select to authenticated
using (public.is_internal_user());

create or replace function public.merge_daily_brand_ad_spend(
    p_brand text,
    p_metric_date date,
    p_naver_ad_spend bigint,
    p_source_details jsonb default '{}'::jsonb
)
returns public.daily_brand_marketing_metrics
language plpgsql
security definer
set search_path = public
as $$
declare
    result public.daily_brand_marketing_metrics;
begin
    if not public.is_internal_user() then raise exception 'not authorized'; end if;

    insert into public.daily_brand_marketing_metrics (
        brand, metric_date, naver_ad_spend, source, source_details, collected_at, updated_at
    )
    values (
        trim(p_brand), p_metric_date, greatest(0, p_naver_ad_spend),
        'api', coalesce(p_source_details, '{}'::jsonb), now(), now()
    )
    on conflict (brand, metric_date) do update
    set naver_ad_spend = excluded.naver_ad_spend,
        source = excluded.source,
        source_details = daily_brand_marketing_metrics.source_details || excluded.source_details,
        collected_at = now(),
        updated_at = now()
    returning * into result;
    return result;
end;
$$;

revoke all on function public.merge_daily_brand_ad_spend(text, date, bigint, jsonb) from public;
grant execute on function public.merge_daily_brand_ad_spend(text, date, bigint, jsonb)
to authenticated, service_role;

update public.marketing_source_mappings mappings
set config = mappings.config || jsonb_build_object(
        'ad_brand', products.brand,
        'ad_customer_id',
        case products.brand
            when '이너리움' then '1226483'
            when '유랄' then '4131809'
        end
    ),
    updated_at = now()
from public.marketing_products products
where products.id = mappings.product_id
  and mappings.provider = 'naver_search'
  and products.brand in ('이너리움', '유랄');
