-- 키워드별 검색량 및 쿠팡 윙/로켓그로스 분리

alter table public.daily_marketing_metrics
    add column if not exists coupang_wing_visits integer check (coupang_wing_visits is null or coupang_wing_visits >= 0),
    add column if not exists coupang_wing_orders integer check (coupang_wing_orders is null or coupang_wing_orders >= 0),
    add column if not exists coupang_wing_revenue bigint check (coupang_wing_revenue is null or coupang_wing_revenue >= 0),
    add column if not exists coupang_growth_visits integer check (coupang_growth_visits is null or coupang_growth_visits >= 0),
    add column if not exists coupang_growth_orders integer check (coupang_growth_orders is null or coupang_growth_orders >= 0),
    add column if not exists coupang_growth_revenue bigint check (coupang_growth_revenue is null or coupang_growth_revenue >= 0);

create table if not exists public.daily_keyword_metrics (
    id bigint generated by default as identity primary key,
    product_id uuid not null references public.marketing_products(id) on delete cascade,
    metric_date date not null,
    keyword text not null check (length(trim(keyword)) > 0),
    search_volume integer not null check (search_volume >= 0),
    source text not null default 'manual' check (source in ('manual', 'api', 'import')),
    source_details jsonb not null default '{}'::jsonb,
    created_by uuid references public.profiles(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (product_id, metric_date, keyword)
);

create index if not exists daily_keyword_metrics_lookup_idx
    on public.daily_keyword_metrics (product_id, keyword, metric_date desc);

alter table public.daily_keyword_metrics enable row level security;
create policy internal_read_daily_keyword_metrics on public.daily_keyword_metrics
for select to authenticated using (public.is_internal_user());

alter table public.keyword_search_snapshots
    add column if not exists keyword text;
update public.keyword_search_snapshots
set keyword = '기존 합계'
where keyword is null;
alter table public.keyword_search_snapshots
    alter column keyword set not null;
alter table public.keyword_search_snapshots
    drop constraint if exists keyword_search_snapshots_product_id_snapshot_date_provider_key;
alter table public.keyword_search_snapshots
    add constraint keyword_search_snapshots_product_date_keyword_provider_key
    unique (product_id, snapshot_date, keyword, provider);

create or replace function public.merge_daily_keyword_metric(
    p_product_id uuid,
    p_metric_date date,
    p_keyword text,
    p_search_volume integer,
    p_source text default 'api',
    p_source_details jsonb default '{}'::jsonb
)
returns public.daily_keyword_metrics
language plpgsql
security definer
set search_path = public
as $$
declare
    result public.daily_keyword_metrics;
    caller_role text := coalesce(auth.jwt() ->> 'role', '');
    effective_source text;
begin
    if not public.is_internal_user() then raise exception 'not authorized'; end if;
    if length(trim(coalesce(p_keyword, ''))) = 0 then raise exception 'keyword is required'; end if;
    effective_source := case
        when caller_role = 'service_role' then p_source
        when p_source = 'import' then 'import'
        else 'manual'
    end;

    insert into public.daily_keyword_metrics (
        product_id, metric_date, keyword, search_volume, source,
        source_details, created_by, updated_at
    )
    values (
        p_product_id, p_metric_date, trim(p_keyword), greatest(0, p_search_volume),
        effective_source, coalesce(p_source_details, '{}'::jsonb), auth.uid(), now()
    )
    on conflict (product_id, metric_date, keyword) do update
    set search_volume = excluded.search_volume,
        source = excluded.source,
        source_details = daily_keyword_metrics.source_details || excluded.source_details,
        updated_at = now()
    returning * into result;
    return result;
end;
$$;

revoke all on function public.merge_daily_keyword_metric(uuid, date, text, integer, text, jsonb) from public;
grant execute on function public.merge_daily_keyword_metric(uuid, date, text, integer, text, jsonb)
to authenticated, service_role;

create or replace function public.merge_daily_coupang_metrics(
    p_product_id uuid,
    p_metric_date date,
    p_patch jsonb
)
returns public.daily_marketing_metrics
language plpgsql
security definer
set search_path = public
as $$
declare
    result public.daily_marketing_metrics;
begin
    if not public.is_internal_user() then raise exception 'not authorized'; end if;

    insert into public.daily_marketing_metrics (product_id, metric_date, created_by)
    values (p_product_id, p_metric_date, auth.uid())
    on conflict (product_id, metric_date) do nothing;

    update public.daily_marketing_metrics m
    set coupang_wing_visits = case when p_patch ? 'coupang_wing_visits' then greatest(0, (p_patch->>'coupang_wing_visits')::integer) else m.coupang_wing_visits end,
        coupang_wing_orders = case when p_patch ? 'coupang_wing_orders' then greatest(0, (p_patch->>'coupang_wing_orders')::integer) else m.coupang_wing_orders end,
        coupang_wing_revenue = case when p_patch ? 'coupang_wing_revenue' then greatest(0, (p_patch->>'coupang_wing_revenue')::bigint) else m.coupang_wing_revenue end,
        coupang_growth_visits = case when p_patch ? 'coupang_growth_visits' then greatest(0, (p_patch->>'coupang_growth_visits')::integer) else m.coupang_growth_visits end,
        coupang_growth_orders = case when p_patch ? 'coupang_growth_orders' then greatest(0, (p_patch->>'coupang_growth_orders')::integer) else m.coupang_growth_orders end,
        coupang_growth_revenue = case when p_patch ? 'coupang_growth_revenue' then greatest(0, (p_patch->>'coupang_growth_revenue')::bigint) else m.coupang_growth_revenue end,
        updated_at = now()
    where m.product_id = p_product_id and m.metric_date = p_metric_date
    returning m.* into result;
    return result;
end;
$$;

revoke all on function public.merge_daily_coupang_metrics(uuid, date, jsonb) from public;
grant execute on function public.merge_daily_coupang_metrics(uuid, date, jsonb)
to authenticated, service_role;

create or replace view public.marketing_okr_rollups
with (security_invoker = true)
as
select
    p.brand,
    m.product_id,
    date_trunc('month', m.metric_date)::date as month_start,
    date_trunc('quarter', m.metric_date)::date as quarter_start,
    date_trunc('year', m.metric_date)::date as year_start,
    sum(case
        when m.blog_views is null and m.cafe_views is null then m.content_views
        else coalesce(m.blog_views, 0) + coalesce(m.cafe_views, 0)
    end)::bigint as content_views,
    sum(m.keyword_search_volume)::bigint as keyword_search_volume,
    sum(
        coalesce(m.cafe24_visits, m.site_visits, 0) +
        coalesce(m.smartstore_visits, 0) +
        case
            when m.coupang_wing_visits is not null or m.coupang_growth_visits is not null
            then coalesce(m.coupang_wing_visits, 0) + coalesce(m.coupang_growth_visits, 0)
            else coalesce(m.coupang_visits, 0)
        end
    )::bigint as visits,
    sum(
        m.cafe24_orders + m.smartstore_orders +
        case
            when m.coupang_wing_orders is not null or m.coupang_growth_orders is not null
            then coalesce(m.coupang_wing_orders, 0) + coalesce(m.coupang_growth_orders, 0)
            else m.coupang_orders
        end
    )::bigint as orders,
    sum(greatest(
        m.cafe24_revenue + m.smartstore_revenue +
        case
            when m.coupang_wing_revenue is not null or m.coupang_growth_revenue is not null
            then coalesce(m.coupang_wing_revenue, 0) + coalesce(m.coupang_growth_revenue, 0)
            else m.coupang_revenue
        end,
        coalesce(m.reported_total_revenue, 0)
    ))::bigint as revenue,
    sum(m.ad_spend)::bigint as ad_spend
from public.daily_marketing_metrics m
join public.marketing_products p on p.id = m.product_id
group by p.brand, m.product_id, date_trunc('month', m.metric_date),
    date_trunc('quarter', m.metric_date), date_trunc('year', m.metric_date);
