-- 장스 마케팅 지수 자동화 및 OKR 기반

alter table public.daily_marketing_metrics
    add column if not exists blog_views integer check (blog_views is null or blog_views >= 0),
    add column if not exists cafe_views integer check (cafe_views is null or cafe_views >= 0),
    add column if not exists cafe24_visits integer check (cafe24_visits is null or cafe24_visits >= 0),
    add column if not exists smartstore_visits integer check (smartstore_visits is null or smartstore_visits >= 0),
    add column if not exists coupang_visits integer check (coupang_visits is null or coupang_visits >= 0),
    add column if not exists reported_total_revenue bigint check (reported_total_revenue is null or reported_total_revenue >= 0),
    add column if not exists data_completeness jsonb not null default '{}'::jsonb,
    add column if not exists collection_status text not null default 'manual'
        check (collection_status in ('complete', 'partial', 'failed', 'manual', 'imported')),
    add column if not exists collected_at timestamptz;

comment on column public.daily_marketing_metrics.blog_views is '해당 일자의 블로그 방문자 수';
comment on column public.daily_marketing_metrics.cafe_views is '해당 일자의 카페 게시글 조회 증가분';
comment on column public.daily_marketing_metrics.cafe24_visits is '자사몰 방문자 수. 기존 site_visits의 명확한 채널 필드';
comment on column public.daily_marketing_metrics.data_completeness is '지표별 수집 여부. 값 0과 미수집을 구분';

-- 기존 값은 자사몰 방문 및 통합 콘텐츠 값으로 보존한다.
update public.daily_marketing_metrics
set cafe24_visits = site_visits
where cafe24_visits is null and site_visits > 0;

create table if not exists public.marketing_targets (
    id bigint generated by default as identity primary key,
    scope_type text not null check (scope_type in ('company', 'brand', 'product')),
    scope_key text not null,
    period_type text not null check (period_type in ('month', 'quarter', 'year')),
    period_start date not null,
    content_views_target bigint not null default 200000 check (content_views_target >= 0),
    traffic_rate_target numeric(7, 4) not null default 10 check (traffic_rate_target > 0),
    conversion_rate_target numeric(7, 4) not null default 10 check (conversion_rate_target > 0),
    keyword_search_target bigint check (keyword_search_target is null or keyword_search_target >= 0),
    orders_target bigint check (orders_target is null or orders_target >= 0),
    revenue_target bigint check (revenue_target is null or revenue_target >= 0),
    ad_spend_budget bigint check (ad_spend_budget is null or ad_spend_budget >= 0),
    created_by uuid references public.profiles(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (scope_type, scope_key, period_type, period_start)
);

create table if not exists public.marketing_source_mappings (
    id uuid primary key default gen_random_uuid(),
    product_id uuid not null references public.marketing_products(id) on delete cascade,
    provider text not null check (provider in (
        'google_sheets', 'cafe24', 'smartstore', 'coupang',
        'naver_search', 'naver_blog', 'naver_cafe', 'generic_json'
    )),
    external_id text,
    config jsonb not null default '{}'::jsonb,
    is_enabled boolean not null default true,
    last_collected_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (product_id, provider, external_id)
);

comment on column public.marketing_source_mappings.config is
    '비밀키를 제외한 상품코드, 키워드, 콘텐츠 URL, 정규화 피드 주소 등의 설정';

create table if not exists public.marketing_ingestion_runs (
    id uuid primary key default gen_random_uuid(),
    provider text not null,
    metric_date date not null,
    status text not null default 'running'
        check (status in ('running', 'success', 'partial', 'failed', 'skipped')),
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    records_succeeded integer not null default 0,
    records_failed integer not null default 0,
    details jsonb not null default '{}'::jsonb,
    error_message text
);

create table if not exists public.marketing_ingestion_batches (
    id uuid primary key default gen_random_uuid(),
    metric_date date not null,
    status text not null default 'running'
        check (status in ('running', 'success', 'partial', 'failed', 'skipped')),
    expected_providers jsonb not null default '[]'::jsonb,
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    trigger_type text not null default 'cron',
    details jsonb not null default '{}'::jsonb
);

alter table public.marketing_ingestion_runs
    add column if not exists batch_id uuid references public.marketing_ingestion_batches(id) on delete set null;

create table if not exists public.marketing_ingestion_errors (
    id bigint generated by default as identity primary key,
    run_id uuid not null references public.marketing_ingestion_runs(id) on delete cascade,
    product_id uuid references public.marketing_products(id) on delete set null,
    provider text not null,
    error_code text,
    message text not null,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.keyword_search_snapshots (
    id bigint generated by default as identity primary key,
    product_id uuid not null references public.marketing_products(id) on delete cascade,
    snapshot_date date not null,
    window_days integer not null default 30 check (window_days > 0),
    search_volume integer not null check (search_volume >= 0),
    provider text not null default 'naver_search',
    collected_at timestamptz not null default now(),
    source_details jsonb not null default '{}'::jsonb,
    unique (product_id, snapshot_date, provider)
);

create index if not exists marketing_targets_lookup_idx
    on public.marketing_targets (scope_type, scope_key, period_type, period_start desc);
create index if not exists marketing_source_mappings_provider_idx
    on public.marketing_source_mappings (provider, is_enabled);
create index if not exists marketing_ingestion_runs_date_idx
    on public.marketing_ingestion_runs (metric_date desc, started_at desc);
create index if not exists marketing_ingestion_batches_date_idx
    on public.marketing_ingestion_batches (metric_date desc, started_at desc);

-- 출처별 부분 업데이트를 원자적으로 수행한다.
-- patch에 없는 필드는 건드리지 않아 API/시트/수동 입력이 서로 0으로 덮지 않는다.
create or replace function public.merge_daily_marketing_metric(
    p_product_id uuid,
    p_metric_date date,
    p_patch jsonb,
    p_source text default 'api',
    p_source_details jsonb default '{}'::jsonb,
    p_collection_status text default 'partial'
)
returns public.daily_marketing_metrics
language plpgsql
security definer
set search_path = public
as $$
declare
    result public.daily_marketing_metrics;
    caller_role text := coalesce(auth.jwt() ->> 'role', '');
    effective_source text;
    effective_status text;
begin
    if not public.is_internal_user() then
        raise exception 'not authorized';
    end if;

    if p_source not in ('manual', 'api', 'import') then
        raise exception 'invalid source';
    end if;

    if p_collection_status not in ('complete', 'partial', 'failed', 'manual', 'imported') then
        raise exception 'invalid collection status';
    end if;

    effective_source := case
        when caller_role = 'service_role' then p_source
        when p_source = 'import' then 'import'
        else 'manual'
    end;
    effective_status := case
        when caller_role = 'service_role' then p_collection_status
        when effective_source = 'import' then 'imported'
        else 'manual'
    end;

    insert into public.daily_marketing_metrics (
        product_id, metric_date, source, source_details, collection_status,
        collected_at, created_by
    )
    values (
        p_product_id, p_metric_date, effective_source, coalesce(p_source_details, '{}'::jsonb),
        effective_status, now(), auth.uid()
    )
    on conflict (product_id, metric_date) do nothing;

    update public.daily_marketing_metrics m
    set
        blog_views = case when p_patch ? 'blog_views' then greatest(0, (p_patch->>'blog_views')::integer) else m.blog_views end,
        cafe_views = case when p_patch ? 'cafe_views' then greatest(0, (p_patch->>'cafe_views')::integer) else m.cafe_views end,
        content_views = case when p_patch ? 'content_views' then greatest(0, (p_patch->>'content_views')::integer) else m.content_views end,
        keyword_search_volume = case when p_patch ? 'keyword_search_volume' then greatest(0, (p_patch->>'keyword_search_volume')::integer) else m.keyword_search_volume end,
        cafe24_visits = case when p_patch ? 'cafe24_visits' then greatest(0, (p_patch->>'cafe24_visits')::integer) else m.cafe24_visits end,
        site_visits = case when p_patch ? 'cafe24_visits' then greatest(0, (p_patch->>'cafe24_visits')::integer)
                           when p_patch ? 'site_visits' then greatest(0, (p_patch->>'site_visits')::integer) else m.site_visits end,
        smartstore_visits = case when p_patch ? 'smartstore_visits' then greatest(0, (p_patch->>'smartstore_visits')::integer) else m.smartstore_visits end,
        coupang_visits = case when p_patch ? 'coupang_visits' then greatest(0, (p_patch->>'coupang_visits')::integer) else m.coupang_visits end,
        tracked_visits = case when p_patch ? 'tracked_visits' then greatest(0, (p_patch->>'tracked_visits')::integer) else m.tracked_visits end,
        tracked_orders = case when p_patch ? 'tracked_orders' then greatest(0, (p_patch->>'tracked_orders')::integer) else m.tracked_orders end,
        cafe24_orders = case when p_patch ? 'cafe24_orders' then greatest(0, (p_patch->>'cafe24_orders')::integer) else m.cafe24_orders end,
        cafe24_revenue = case when p_patch ? 'cafe24_revenue' then greatest(0, (p_patch->>'cafe24_revenue')::bigint) else m.cafe24_revenue end,
        smartstore_orders = case when p_patch ? 'smartstore_orders' then greatest(0, (p_patch->>'smartstore_orders')::integer) else m.smartstore_orders end,
        smartstore_revenue = case when p_patch ? 'smartstore_revenue' then greatest(0, (p_patch->>'smartstore_revenue')::bigint) else m.smartstore_revenue end,
        coupang_orders = case when p_patch ? 'coupang_orders' then greatest(0, (p_patch->>'coupang_orders')::integer) else m.coupang_orders end,
        coupang_revenue = case when p_patch ? 'coupang_revenue' then greatest(0, (p_patch->>'coupang_revenue')::bigint) else m.coupang_revenue end,
        reported_total_revenue = case when p_patch ? 'reported_total_revenue' then greatest(0, (p_patch->>'reported_total_revenue')::bigint) else m.reported_total_revenue end,
        ad_spend = case when p_patch ? 'ad_spend' then greatest(0, (p_patch->>'ad_spend')::bigint) else m.ad_spend end,
        data_completeness = coalesce(m.data_completeness, '{}'::jsonb) || coalesce(p_patch->'data_completeness', '{}'::jsonb),
        source = effective_source,
        source_details = coalesce(m.source_details, '{}'::jsonb) || coalesce(p_source_details, '{}'::jsonb),
        collection_status = effective_status,
        collected_at = now(),
        updated_at = now()
    where m.product_id = p_product_id and m.metric_date = p_metric_date
    returning m.* into result;

    if p_patch ? 'blog_views' or p_patch ? 'cafe_views' then
        update public.daily_marketing_metrics m
        set content_views = coalesce(m.blog_views, 0) + coalesce(m.cafe_views, 0)
        where m.product_id = p_product_id and m.metric_date = p_metric_date
        returning m.* into result;
    end if;

    return result;
end;
$$;

revoke all on function public.merge_daily_marketing_metric(uuid, date, jsonb, text, jsonb, text) from public;
grant execute on function public.merge_daily_marketing_metric(uuid, date, jsonb, text, jsonb, text)
    to authenticated, service_role;

alter table public.marketing_targets enable row level security;
alter table public.marketing_source_mappings enable row level security;
alter table public.marketing_ingestion_runs enable row level security;
alter table public.marketing_ingestion_batches enable row level security;
alter table public.marketing_ingestion_errors enable row level security;
alter table public.keyword_search_snapshots enable row level security;

create policy internal_read_marketing_targets on public.marketing_targets
for select to authenticated using (public.is_internal_user());
create policy admin_manage_marketing_targets on public.marketing_targets
for all to authenticated using (public.is_current_user_admin()) with check (public.is_current_user_admin());

create policy internal_read_marketing_mappings on public.marketing_source_mappings
for select to authenticated using (public.is_internal_user());
create policy admin_manage_marketing_mappings on public.marketing_source_mappings
for all to authenticated using (public.is_current_user_admin()) with check (public.is_current_user_admin());

create policy internal_read_marketing_runs on public.marketing_ingestion_runs
for select to authenticated using (public.is_internal_user());
create policy internal_read_marketing_batches on public.marketing_ingestion_batches
for select to authenticated using (public.is_internal_user());
create policy internal_read_marketing_errors on public.marketing_ingestion_errors
for select to authenticated using (public.is_internal_user());
create policy internal_read_keyword_search_snapshots on public.keyword_search_snapshots
for select to authenticated using (public.is_internal_user());

-- 브랜드별 기본 월 목표. 제품 데이터는 화면에서 브랜드 단위로 합산한다.
insert into public.marketing_targets (
    scope_type, scope_key, period_type, period_start, content_views_target,
    traffic_rate_target, conversion_rate_target
)
select 'brand', brand, 'month', date_trunc('month', current_date)::date, 200000, 10, 10
from (select distinct brand from public.marketing_products where is_active) brands
on conflict (scope_type, scope_key, period_type, period_start) do nothing;

insert into public.marketing_source_mappings (product_id, provider, external_id, config, is_enabled)
select
    id,
    'naver_search',
    slug,
    jsonb_build_object(
        'keywords',
        case slug
            when 'innerium-gala431' then jsonb_build_array('이너리움 갈라431', '갈라431')
            when 'innerium-minti431' then jsonb_build_array('이너리움 민티431', '민티431')
            when 'yural-tonggam-cream' then jsonb_build_array('유랄 통감크림', '통감크림')
            when 'yural-myeongga-bonhwan' then jsonb_build_array('유랄 명가본환', '명가본환')
            else jsonb_build_array(name)
        end
    ),
    false
from public.marketing_products
where is_active
on conflict (product_id, provider, external_id) do nothing;

-- Dashboard에서 분기·연간 OKR을 같은 일별 원천 데이터로 조회한다.
create or replace view public.marketing_okr_rollups
with (security_invoker = true)
as
select
    p.brand,
    m.product_id,
    date_trunc('month', m.metric_date)::date as month_start,
    date_trunc('quarter', m.metric_date)::date as quarter_start,
    date_trunc('year', m.metric_date)::date as year_start,
    sum(case
        when m.blog_views is null and m.cafe_views is null then m.content_views
        else coalesce(m.blog_views, 0) + coalesce(m.cafe_views, 0)
    end)::bigint as content_views,
    sum(m.keyword_search_volume)::bigint as keyword_search_volume,
    sum(coalesce(m.cafe24_visits, m.site_visits, 0) + coalesce(m.smartstore_visits, 0) + coalesce(m.coupang_visits, 0))::bigint as visits,
    sum(m.cafe24_orders + m.smartstore_orders + m.coupang_orders)::bigint as orders,
    sum(greatest(
        m.cafe24_revenue + m.smartstore_revenue + m.coupang_revenue,
        coalesce(m.reported_total_revenue, 0)
    ))::bigint as revenue,
    sum(m.ad_spend)::bigint as ad_spend
from public.daily_marketing_metrics m
join public.marketing_products p on p.id = m.product_id
group by p.brand, m.product_id, date_trunc('month', m.metric_date),
    date_trunc('quarter', m.metric_date), date_trunc('year', m.metric_date);

grant select on public.marketing_okr_rollups to authenticated;

-- Supabase Vault에 아래 비밀값을 등록한 뒤 매일 00:00 UTC(09:00 KST)에 호출된다.
-- marketing_collector_url: https://<project-ref>.supabase.co/functions/v1/collect-marketing
-- marketing_collector_token: Edge Function의 COLLECTOR_SECRET과 같은 값
create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists pg_net with schema extensions;

create or replace function public.invoke_marketing_collector()
returns bigint
language plpgsql
security definer
set search_path = public, vault, extensions
as $$
declare
    collector_url text;
    collector_token text;
    request_id bigint;
begin
    select decrypted_secret into collector_url
    from vault.decrypted_secrets where name = 'marketing_collector_url' limit 1;
    select decrypted_secret into collector_token
    from vault.decrypted_secrets where name = 'marketing_collector_token' limit 1;

    if collector_url is null or collector_token is null then
        raise exception 'marketing collector Vault secrets are not configured';
    end if;

    select net.http_post(
        url := collector_url,
        headers := jsonb_build_object(
            'Content-Type', 'application/json',
            'x-collector-secret', collector_token
        ),
        body := jsonb_build_object(
            'metric_date', (timezone('Asia/Seoul', now())::date - 1)::text,
            'trigger', 'cron'
        )
    ) into request_id;
    return request_id;
end;
$$;

do $$
declare
    existing_job bigint;
begin
    select jobid into existing_job from cron.job where jobname = 'marketing-daily-0900-kst';
    if existing_job is not null then
        perform cron.unschedule(existing_job);
    end if;
    perform cron.schedule(
        'marketing-daily-0900-kst',
        '0 0 * * *',
        'select public.invoke_marketing_collector();'
    );
end;
$$;
